### ISSUE TITLE
Add possibility to receive bytes in request (to allow i.e. to receive images).

### ISSUE THREAD

**Issue by mrozigor** [mrozigor/crow#4]
In response to https://github.com/ipkn/crow/issues/371

**Comment by The-EDev** [comment]
I believe the original issue (#371) is about sending byte data from a client to the server.

as for sending bytes in a response, I believe we would only need to convert the bytes to text since HTTP/1 uses text anyway.

**Comment by mrozigor** [comment]
Mea culpa, fixed description ;)

**Comment by The-EDev** [comment]
I should also mention that this would probably require parsing multipart/form-data types, since that's the main way files (such as images) are sent to an API.

**Comment by The-EDev** [comment]
Ok so I did some research and a bit of testing, I was wrong earlier, you **do not** need a multipart content type to send a file, and if the body is a file, it can be simply moved around as a string, and written to a file using `std::ofstream`. This is the code:
```c++
CROW_ROUTE(app, "/jpg")
([](const crow::request& req, crow::response& res) 
{    
    std::ofstream outputFile("cat2.jpg", std::ios::out | std::ios::binary);
    outputFile << req.body;
    
    res.set_static_file_info("cat2.jpg");
    res.end();
}
```

so I don't believe _this_ is the issue, but rather parsing `multipart/form-data` (with files inside). Since that's how most web pages or clients send files to a server.

**Comment by choice17** [comment]
@The-EDev  is there any way to parse multipart/form-data with multiple payloads by their names in single request?
like image/ shape/ other info ?

**Comment by The-EDev** [comment]
I have a PR (#15) to add multipart support, this includes parsing, data storage, and serialization.

you should be able to pass a request and you get this data structure:
```
| Message                                                       |
| Headers                 | Parts                               |
| value | Parameters      | Headers            | body (payload) |
                          | value | Parameters |   
```
the type should be in the `Part`'s `Content-Type` header

**Comment by choice17** [comment]
> I have a PR (#15) to add multipart support, this includes parsing, data storage, and serialization.
> 
> you should be able to pass a request and you get this data structure:
> 
> ```
> | Message                                                       |
> | Headers                 | Parts                               |
> | value | Parameters      | Headers            | body (payload) |
>                           | value | Parameters |   
> ```
> 
> once the PR is merged you'll be able to call `crow::multipart::message msg(req)` with `req` being your request, and then call something like `mydata = msg.parts[2].body`

Just checked the PR, it works! Thanks.
