### ISSUE TITLE
static directory support

### ISSUE THREAD

**Issue by The-EDev** [mrozigor/crow#41]
Have the `/static` directory be fully accessible to clients, this is similar to how Flask handles static files.

This can be done either by having a `/static/<path>` rule be always present (possible with an option to disable it). or with middleware that checks for any requests that start with `/static` and just does a `set_static_file_info` to whatever the request url is.

ipkn#386 is somewhat related.

**Comment by mrozigor** [comment]
Or maybe implement middleware with parameter that specify static files route prefix.

**Comment by The-EDev** [comment]
That is possible, but my worry with middlewares is that they run on every request, so no matter the request, it will still be checked.
I'm not sure what impact this has on performance. I also think static file support is quite fundamental to any web server. Which is why I suggested the permanent route.

**Comment by The-EDev** [comment]
Holy c$%^ I didn't realize it was this simple, I think it's done XD, making new branch now
