### ISSUE TITLE
Separate middleware.h from the main project

### ISSUE THREAD

**Issue by The-EDev** [mrozigor/crow#49]
`middleware.h` only contains a cookie handling middleware, while it's important to handle cookies, the middleware isn't being used by any core part, neither is it necessary to run a basic server.

I suggest separating the cookie parser and more middlewares into a separate repository. or at least a name change.

@mrozigor what do you think?

**Comment by mrozigor** [comment]
Hmm, I'm not sure. I think that some middlewares are important and should be distributed with framework. Maybe add a option to build crow with only selected middlewares?

**Comment by The-EDev** [comment]
I'm guessing by build you mean creating `crow_all.h`, I do agree with you on some middlewares being important, but I don't think we need to have them as part of the core header library, maybe we can put them in a separate `middlewares` directory outside `include` or `include/crow` and have the users selectively import those into their projects.
what do you think? is that good or should some middlewares be part of `crow_all.h`?

**Comment by mrozigor** [comment]
I think that middlewares should be extracted to their own directory. But I think that merging library to `crow_all.h` should also include selected middlewares (f.e. user pass flag `--middlewares auth,cookies` to merge script).

**Comment by The-EDev** [comment]
Alright, sounds good to me.
