### ISSUE TITLE
Extra Documentation

### ISSUE THREAD

**Issue by The-EDev** [mrozigor/crow#60]
So the API reference is coming along nicely (about as nice as trying to type what I learned in the past 20 minutes in a coherent readable manner). 

But I don't believe this is it, sure it is helpful if someone wants to go to the next level in using crow (or even editing it). But there should be something for people who are just starting out with Crow or C++ even (me 2 months ago).

Currently we have examples to fulfill this role. But I get the feeling They're not enough. Things like setting up the environment, connecting to a proxy, compiling with SSL, creating middlewares, even creating crow_all.h are not in these examples, and frankly the examples themselves aren't documented, they don't mention any quirks or tricks that might come up, nor do they explain why things are the way they are.

To be frank, currently our documentation mirrors that of ASIO, which holy crap do I hate going through.

So the solution in my opinion is having the API reference (doxygen stuff) be only 1 part of a much larger documentation effort, @ipkn was trying to accomplish this via the wiki. This could be done the same way or through increasing the size of the github.io to add tutorials, introductions, and explanations (they all probably mean the same thing I'm just overexpressing).

We can later move this out of github.io into our own website, I mean.. we have a logo, the only thing left is everything else.

I believe this is an important step to take for crow to go from "just another C++ project" to something actually viable in a production environment, and I would like it if we could do this either before or around v0.3 (I know the line between0.3 and 1.0 is getting more and more blurry).

**Comment by vexy** [comment]
What if we setup a "Project" and interlink all the issues/tasks. If nothing else, that might clarify the line between v0.3 and v1.0 ?

**Comment by The-EDev** [comment]
@vexy Well there already is a v0.3 milestone which I believe is good enough to know which issues belong where. 

What I actually meant when I said "the line between 0.3 and 1.0 is getting more and more blurry" is that there might not be a need to release another "Pre-Release" version and just release v1.0 since by then Crow would've matured enough for a production environment.

**Comment by The-EDev** [comment]
I need help with the following:
- Building with Visual Studio on windows (for debug and release + adding macro definitions)
- Setting up a proxy using Nginx and Apache2

**Comment by The-EDev** [comment]
@mrozigor I believe your website runs on crow behind nginx, if i'm not wrong, could you please have some steps on how you got it working?

**Comment by mrozigor** [comment]
Maybe, but this is probably done by my hosting company. I've only reserved port and run crow on it.
