### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by The-EDev** [mrozigor/crow#7]
in response to https://github.com/ipkn/crow/issues/45, https://github.com/ipkn/crow/issues/180, https://github.com/ipkn/crow/issues/288.

We could either use the wiki and just explain things or set something like doxygen up.

either way some explanation as to how every part works and some form of API reference is needed.

**Comment by mrozigor** [comment]
I think that properly maintained doxygen will be ok. I'll try to find how to connect it with github, to automatically generate documentation here.

**Comment by The-EDev** [comment]
[this](https://gist.github.com/vidavidorra/548ffbcdae99d752da02) might be helpful.

**Comment by mrozigor** [comment]
I've found the same one yesterday :D
