### ISSUE TITLE
Run Travis CI

### ISSUE THREAD

**Issue by The-EDev** [mrozigor/crow#9]
We have .travis.yml, we just might need to change things like the compiler or notification channel, and we'll be able to run unit tests again.

#7 probably depends on this.

**Comment by The-EDev** [comment]
note: it could be helpful to add `-V` (verbose) parameter to the `ctest -j2` command (so we know which part of the test is actually failing)

**Comment by The-EDev** [comment]
I've gotten `.travis.yml` to work on my repo, the new parameters are `gcc8`, `9(default)`, and `10`, and `clang`, also changed OS to `focal`, and `boost` to `1.71`. 
I also removed the notification part because well.. I have no clue who owns `#crow`, and going to that room, it's pretty empty.

Should I open a PR now or after #7 is also sorted?

**Comment by mrozigor** [comment]
I think that documentation part could be done later. I didn't even know about `#crow` ;)
